document.writeln("<div class=\"w_230\">");
document.writeln("            <div class=\"nav\">");
document.writeln("            	<ul>");
document.writeln("                  <li><a href=\"index.html\">首页</a>");
document.writeln("                  	<ul>");
document.writeln("                       <li><a href=\"index.html#jianjie\"><font>-- 会议简介</font></a></li>");
document.writeln("                       <li><a href=\"index.html#liangdian\">-- 大会亮点</a></li>");
document.writeln("                       <li><a href=\"index.html#fangxiang\">-- 主要议题方向</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"#\">具体安排</a>");
document.writeln("                  <ul>");
document.writeln("                            <li><a href=\"richeng.html\">-- 会议日程</a></li>");
document.writeln("                        	<li><a href=\"jiabin.html\">-- 嘉宾介绍</a></li>");
document.writeln("                            <li><a href=\"#\"><font>-- 我要参会</font></a><img src=\"images/new.gif\"></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"zhanshi.html\">参与方式</a>");
document.writeln("                  	<ul>");
document.writeln("                            <li><a href=\"zhanshi.html\">-- 展览展示</a></li>");
document.writeln("                        	<li><a href=\"zanzhu.html\">-- 参与方式</a></li>");
document.writeln("                        </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"meiti.html\">媒体中心</a>");
document.writeln("                  	<ul>");
document.writeln("                            <li><a href=\"meiti.html\">-- 媒体合作</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("			<div class=\"huiz mtop\">");
document.writeln("            	<div class=\"tite\"><h3>联系我们</h3>");
document.writeln("            	</div>");
document.writeln("                <div class=\"tong\">");
document.writeln("				<p><strong>会议合作：</strong><br>");
document.writeln("");
document.writeln("李泽<br>");
document.writeln("Tel:+86-022-58168873<br>");
document.writeln("Fax:+86-022-58168885<br>");
document.writeln("");
document.writeln("</p>");
document.writeln("</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("		");
document.writeln("		");
document.writeln("		<div class=\"huiz mtop\">");
document.writeln("            	");
document.writeln("                <div class=\"tong\">");
document.writeln("				<p><a href=\"http://kjtxw.com/index.php/Keji/index/plates\" target=\"_blank\"><img src=\"images/kjtxw.jpg\" border=\"0\"></a></p>");
document.writeln("				<p><a href=\"http://www.cipeasia.com/\" target=\"_blank\"><img src=\"images/photonicschina-cipe.jpg\" border=\"0\"></a></p>");
document.writeln("				<p><a href=\"http://www.jingqiahui.com.cn/\" target=\"_blank\"><img src=\"images/photonicschina-jingqiahui.jpg\" border=\"0\"></a></p>");
document.writeln("				<p><a href=\"http://www.cnoenet.com/aopc/\" target=\"_blank\"><img src=\"images/photonicschina-aopc.jpg\" border=\"0\"></a></p>");
document.writeln("                </div>");
document.writeln("            </div>	");
document.writeln("        </div>");
document.writeln("		");
document.writeln("");