document.writeln("<div class=\"w_230\">");
document.writeln("            <div class=\"nav\">");
document.writeln("            	<ul>");
document.writeln("                  <li><a href=\"index-en.html\">Homepage</a>");
document.writeln("                  	<ul>");
document.writeln("                       <li><a href=\"index-en.html#jianjie\"><font>-- Introduction</font></a></li>");
document.writeln("                       <li><a href=\"index-en.html#liangdian\">-- Highlights</a></li>");
document.writeln("                       <li><a href=\"index-en.html#fangxiang\">-- Main topics</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"#\">Meeting Hgenda</a>");
document.writeln("                  <ul>");
document.writeln("                            <li><a href=\"#\">-- schedule</a></li>");
document.writeln("                        	<li><a href=\"#\">-- Introduction guests</a></li>");
document.writeln("                            <li><a href=\"http://www.manuscript-cnoenet.com/index_en.htm\" target=\"_blank\"><font>-- Call for Papers</font></a><img src=\"images/new.gif\"></li>");
document.writeln("                            <li><a href=\"http://www.cnoenet.com/meeting/jqh2015.asp?id=38\" target=\"_blank\"><font>-- Join Us</font></a><img src=\"images/new.gif\"></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"zhanshi.html\">value-added services</a>");
document.writeln("                  	<ul>");
document.writeln("                        	<li><a href=\"zanzhu-en.html\">-- Sponsorship scheme</a></li>");
document.writeln("                            <li><a href=\"zhanshi-en.html\">-- Exhibits</a></li>");
document.writeln("                            <li><a href=\"http://en.jingqiahui.com.cn/\" target=\"_blank\">-- Concurrent Event</a></li>");
document.writeln("                        </ul>");
document.writeln("                  </li>");
document.writeln("                  <li><a href=\"meiti.html\">Media Center</a>");
document.writeln("                  	<ul>");
document.writeln("                            <li><a href=\"meiti-en.html\">-- Media Cooperation</a></li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("			<div class=\"huiz mtop\">");
document.writeln("            	<div class=\"tite\"><h3>Contact</h3>");
document.writeln("            	</div>");
document.writeln("                <div class=\"tong\">");
document.writeln("				<p>");
document.writeln("");
document.writeln("Wang Ying <br>");
document.writeln("Phone：022-58628871<br>");
document.writeln("Email：wallen.22@163.com");
document.writeln("");
document.writeln("</p>");
document.writeln("</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("		");
document.writeln("");
