
<field:Gender itemname="Gender" autofield="1" type="radio" isnull="true" default="Mr,Miss"  maxlength="250" page="">
</field:Gender>

<field:Name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:Name>

<field:Position itemname="Position" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:Position>

<field:Deparment itemname="Deparment" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:Deparment>

<field:PostCode itemname="Post Code" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:PostCode>

<field:Company itemname="Company" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:Company>

<field:CompanyAddress itemname="Company Address" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:CompanyAddress>

<field:Country itemname="Country" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:Country>

<field:City itemname="City" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:City>
