
<field:gender itemname="Gender" autofield="1" type="radio" isnull="true" default="Mr,Miss"  maxlength="250" page="">
</field:gender>

<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:position itemname="Position" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:position>

<field:deparment itemname="Deparment" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:deparment>

<field:postcode itemname="Post Code" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:postcode>

<field:company itemname="Company" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:companyaddress itemname="Company Address" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:companyaddress>

<field:country itemname="Country" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:country>

<field:city itemname="City" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:city>

<field:telephone itemname="Telephone" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:telephone>

<field:fax itemname="Fax" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:fax>

<field:mobilephone itemname="Mobile Phone" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobilephone>
