
<field:gender itemname="Gender" autofield="1" type="radio" isnull="true" default="Mr,Miss"  maxlength="250" page="">
</field:gender>

<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:position itemname="Position" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:position>

<field:deparment itemname="Deparment" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:deparment>

<field:postcode itemname="Post Code" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:postcode>

<field:company itemname="Company" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:companyaddress itemname="Company Address" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:companyaddress>

<field:country itemname="Country" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:country>

<field:city itemname="City" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:city>

<field:telephone itemname="Telephone" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:telephone>

<field:fax itemname="Fax" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:fax>

<field:mobilephone itemname="Mobile Phone" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mobilephone>

<field:email itemname="Email" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:website itemname="Website" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:website>

<field:mainproduct itemname="Main Product" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:mainproduct>

<field:rawtype1 itemname="Select Booth" autofield="1" type="radio" isnull="true" default="Island Standard,Standard Booth(3m*3m)"  maxlength="250" page="">
</field:rawtype1>

<field:area itemname="Area of Booth" autofield="1" type="select" isnull="true" default="9 square meters,18 square meters,27 square meters,36 square meters,45 square meters,More than 100 square meters"  maxlength="250" page="">
</field:area>
