<?php
$z[0]=Array("field","",183,205);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",206,232);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",704,739);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",810,866);
$z[3][4]['name']="position";
$z[3][4]['function']="strip_tags(@me)";
$z[4]=Array("field","",968,990);
$z[4][4]['name']="seotitle";
$z[5]=Array("field","",998,1019);
$z[5][4]['name']="content";

?>