
<field:gender itemname="Gender" autofield="1" type="radio" isnull="true" default="Mr,Miss"  maxlength="250" page="">
</field:gender>

<field:name itemname="Name" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:position itemname="Position" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:position>

<field:deparment itemname="Deparment" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:deparment>

<field:postcode itemname="Post Code" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:postcode>
