<?php
$z[0]=Array("arclist","\n   <DD><A title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/] </A></DD>\n  ",4420,4577);
$z[0][4]['typeid']="19";
$z[0][4]['titlelen']="120";
$z[1]=Array("arclist","\n   <DD><A title=\"[field:title/]\" href=\"[field:arcurl/]\" target=\"_blank\">[field:title/] </A></DD>\n  ",4736,4893);
$z[1][4]['typeid']="20";
$z[1][4]['titlelen']="120";

?>