<?php
$z[0]=Array("field","",183,205);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",206,232);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",704,739);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",810,866);
$z[3][4]['name']="position";
$z[3][4]['function']="strip_tags(@me)";
$z[4]=Array("field","",872,891);
$z[4][4]['name']="title";
$z[5]=Array("list","\n  <DD><SPAN class=time>[field:pubdate function=\"GetDateMK(@me)\"/] </SPAN> <A title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</A>\n   ",1069,1251);
$z[5][4]['pagesize']="8";
$z[6]=Array("pagelist","",1280,1351);
$z[6][4]['listitem']="info,index,end,pre,next,pageno";
$z[6][4]['listsize']="5";

?>