document.writeln("<div class=\"w_235\">");
document.writeln("		  <div ><img src=\"images/en.gif\" border=\"0\" usemap=\"#Map\" />");
document.writeln("<map name=\"Map\">");
document.writeln("  <area shape=\"rect\" coords=\"33,0,111,25\" href=\"http://www.cipeasia.com/ONOI/\">");
document.writeln("<area shape=\"rect\" coords=\"121,-2,213,19\" href=\"http://www.cipeasia.com/ONOI/index-en.html\" target=\"_blank\">");
document.writeln("</map></div>");
document.writeln("       	  <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>主办单位</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("              中国高科技产业化研究会<br>");
document.writeln("			  中国光学工程学会");
document.writeln("		    </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>承办单位</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            中国高科技产业化研究会产学研合作协调部");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>联办单位</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            中国联通<br>");
document.writeln("            下一代互联网接入系统国家工程实验室<br>");
document.writeln("            武汉物联网联盟");
document.writeln("");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>支持单位</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            中国物联网研究发展中心");
document.writeln("            ");
document.writeln("");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("          ");
document.writeln("          <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>媒体支持</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            	   <a href=\"http://www.cctime.com/\" target=\"_blank\"><img src=\"images/cctime_logo.gif\" border=\"0\" /></a><br /><br />");
document.writeln("				   <a href=\"http://www.lwc.com.cn/\" target=\"_blank\"><img src=\"images/lwc_logo.jpg\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.sensorshome.com/\" target=\"_blank\"><img src=\"images/sensorshome_logo.jpg\" width=\"196\" height=\"76\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.rfidchina.org/\" target=\"_blank\"><img src=\"images/rfidchina_logo.gif\" width=\"196\" height=\"76\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.rfidworld.com.cn/\" target=\"_blank\"><img src=\"images/rfidworld_logo.gif\" border=\"0\" /></a></div>");
document.writeln("  </div>");
document.writeln("      </div>");