document.writeln("<div id=\"bottom\">");
document.writeln("        <div class=\"bottom-2\">");
document.writeln("		客服热线：+86-022-58168871 客服传真：+86-022-58168885");
document.writeln("		<br>");
document.writeln("		业务联系：+86-022-58168871");
document.writeln("		<br>");
document.writeln("		Copyright ©  2015, All Rights Reserved.");
document.writeln("		</div>");
document.writeln("	");
document.writeln("        ");
document.writeln("    </div>");