document.writeln("<div class=\"w_235\">");
document.writeln("<div class=\"w_235\">");
document.writeln("		  <div ><img src=\"images/en.gif\" border=\"0\" usemap=\"#Map\" />");
document.writeln("<map name=\"Map\">");
document.writeln("  <area shape=\"rect\" coords=\"33,0,111,25\" href=\"http://www.cipeasia.com/ONOI/\" target=\"_blank\">");
document.writeln("<area shape=\"rect\" coords=\"121,-2,213,19\" href=\"http://www.cipeasia.com/ONOI/index-en.html\">");
document.writeln("</map></div>");
document.writeln("       	  <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>Sponsors</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("              China high-tech Industrialization Association<br>");
document.writeln("			  China Society for Optical Engineering");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>Organizers</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            China high-tech Industrialization Association Production-study-research cooperation coordination department");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>Co-Sponsors</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("           China-Wuhan, Light Valley networking industry technology innovation alliance<br>");
document.writeln("China Unicom<br>");
document.writeln("National Engineer Laboratory for Next Generation internet Access System");
document.writeln("");
document.writeln("");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		    <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>Supporters</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            China Research and Development Center of Things");
document.writeln("");
document.writeln("");
document.writeln("			  </div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("		  <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3><a href=\"schedule.html#jieshao\">Guests</a></h3></div>");
document.writeln("            <div class=\"wei\"> ");
document.writeln("            	<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"91%\" style=\"margin-bottom:5px;\">");
document.writeln("		<tr>");
document.writeln("				<td width=\"34%\" valign=\"top\"><img src=\"images/jb01.jpg\" border=\"0\" /></td>");
document.writeln("				<td width=\"66%\" valign=\"top\" style=\"padding-left:5px;\">");
document.writeln("				<strong>Hquan Wu</strong><br />");
document.writeln("				Chinese Academy of engineering,The expert of Optical fiber transmission network and broadband information network");
document.writeln("				");
document.writeln("				</td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"91%\" style=\"margin-bottom:5px;\">");
document.writeln("		<tr>");
document.writeln("				<td width=\"34%\" valign=\"top\"><img src=\"images/jb02.jpg\" border=\"0\" /></td>");
document.writeln("				<td width=\"66%\" valign=\"top\" style=\"padding-left:5px;\">");
document.writeln("				<strong>Xiongyan Tang</strong><br />");
document.writeln("				Professor Senior Engineer，expert enjoying the special government allowance, person selected for New Century Talents Project.");
document.writeln("				");
document.writeln("				</td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"91%\" style=\"margin-bottom:5px;\">");
document.writeln("		<tr>");
document.writeln("				<td width=\"34%\" valign=\"top\"><img src=\"images/jb03.jpg\" border=\"0\" /></td>");
document.writeln("				<td width=\"66%\" valign=\"top\" style=\"padding-left:5px;\">");
document.writeln("				<br /><strong>Deming Liu</strong><br />");
document.writeln("				The next generation access network engineering laboratory director of hubei province");
document.writeln("				");
document.writeln("				</td>");
document.writeln("		</tr>");
document.writeln("</table>");
document.writeln("");
document.writeln("			</div>");
document.writeln("          </div>");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("          ");
document.writeln("		  ");
document.writeln("		  ");
document.writeln("          ");
document.writeln("          <div class=\"dan mtop\">");
document.writeln("          	<div class=\"tite\"><h3>Media support</h3></div>");
document.writeln("            <div class=\"wei\">");
document.writeln("            	   <a href=\"http://www.cctime.com/\" target=\"_blank\"><img src=\"images/cctime_logo.gif\" border=\"0\" /></a><br /><br />");
document.writeln("				   <a href=\"http://www.lwc.com.cn/\" target=\"_blank\"><img src=\"images/lwc_logo.jpg\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.sensorshome.com/\" target=\"_blank\"><img src=\"images/sensorshome_logo.jpg\" width=\"196\" height=\"76\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.rfidchina.org/\" target=\"_blank\"><img src=\"images/rfidchina_logo.gif\" width=\"196\" height=\"76\" border=\"0\" /></a><br /><br />");
document.writeln("                   <a href=\"http://www.rfidworld.com.cn/\" target=\"_blank\"><img src=\"images/rfidworld_logo.gif\" border=\"0\" /></a></div>");
document.writeln("            </div>");
document.writeln("      </div>");